[package]
name = "cratelib"
version = "0.1.0"
edition = "2021"
autobins = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# binaries
[[bin]]
name = "app"
path = "bin/app.rs"

